#
# ALGAE Runtime Service Build Configuration
# Copyright (c) 2025, Ian Moffett and the Algae team.
# All rights reserved.
# Provided under the BSD 3-Clause license.
#

.PHONY: all
all: csrs

.PHONY: csrs
csrs:
	cd csrs/; make
